// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CancellationService is an autogenerated mock type for the CancellationService type
type CancellationService struct {
	mock.Mock
}

// ProcessOddRecordCancellation provides a mock function with given fields: ctx
func (_m *CancellationService) ProcessOddRecordCancellation(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessOddRecordCancellation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCancellationService creates a new instance of CancellationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCancellationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CancellationService {
	mock := &CancellationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
