// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "transaction-processor/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *TransactionService) GetBalance(ctx context.Context, userID int64) (*model.BalanceResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *model.BalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.BalanceResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.BalanceResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *TransactionService) GetTransactionsByUser(ctx context.Context, userID int64, limit int, offset int) ([]*model.Transaction, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByUser")
	}

	var r0 []*model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]*model.Transaction, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []*model.Transaction); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessTransaction provides a mock function with given fields: ctx, req, sourceType, userID
func (_m *TransactionService) ProcessTransaction(ctx context.Context, req *model.TransactionRequest, sourceType model.SourceType, userID int64) (*model.TransactionResponse, error) {
	ret := _m.Called(ctx, req, sourceType, userID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTransaction")
	}

	var r0 *model.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TransactionRequest, model.SourceType, int64) (*model.TransactionResponse, error)); ok {
		return rf(ctx, req, sourceType, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TransactionRequest, model.SourceType, int64) *model.TransactionResponse); ok {
		r0 = rf(ctx, req, sourceType, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TransactionRequest, model.SourceType, int64) error); ok {
		r1 = rf(ctx, req, sourceType, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
