// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// DBManager is an autogenerated mock type for the DBManager type
type DBManager struct {
	mock.Mock
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *DBManager) WithTransaction(ctx context.Context, fn func(pgx.Tx) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(pgx.Tx) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDBManager creates a new instance of DBManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBManager {
	mock := &DBManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
