// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "transaction-processor/internal/model"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// CancelTransactionIfProcessed provides a mock function with given fields: ctx, id, tx
func (_m *TransactionRepository) CancelTransactionIfProcessed(ctx context.Context, id int64, tx pgx.Tx) (bool, error) {
	ret := _m.Called(ctx, id, tx)

	if len(ret) == 0 {
		panic("no return value specified for CancelTransactionIfProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, pgx.Tx) (bool, error)); ok {
		return rf(ctx, id, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, pgx.Tx) bool); ok {
		r0 = rf(ctx, id, tx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, pgx.Tx) error); ok {
		r1 = rf(ctx, id, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestOddProcessedTransactions provides a mock function with given fields: ctx, limit
func (_m *TransactionRepository) GetLatestOddProcessedTransactions(ctx context.Context, limit int) ([]*model.Transaction, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestOddProcessedTransactions")
	}

	var r0 []*model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*model.Transaction, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*model.Transaction); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransaction provides a mock function with given fields: ctx, transactionID, tx
func (_m *TransactionRepository) GetTransaction(ctx context.Context, transactionID string, tx ...pgx.Tx) (*model.Transaction, error) {
	_va := make([]interface{}, len(tx))
	for _i := range tx {
		_va[_i] = tx[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, transactionID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...pgx.Tx) (*model.Transaction, error)); ok {
		return rf(ctx, transactionID, tx...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...pgx.Tx) *model.Transaction); ok {
		r0 = rf(ctx, transactionID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...pgx.Tx) error); ok {
		r1 = rf(ctx, transactionID, tx...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *TransactionRepository) GetTransactionsByUser(ctx context.Context, userID int64, limit int, offset int) ([]*model.Transaction, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByUser")
	}

	var r0 []*model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]*model.Transaction, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []*model.Transaction); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTransaction provides a mock function with given fields: ctx, trans, tx
func (_m *TransactionRepository) InsertTransaction(ctx context.Context, trans *model.Transaction, tx pgx.Tx) error {
	ret := _m.Called(ctx, trans, tx)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Transaction, pgx.Tx) error); ok {
		r0 = rf(ctx, trans, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LockTransactionForCancellation provides a mock function with given fields: ctx, id, tx
func (_m *TransactionRepository) LockTransactionForCancellation(ctx context.Context, id int64, tx pgx.Tx) (bool, error) {
	ret := _m.Called(ctx, id, tx)

	if len(ret) == 0 {
		panic("no return value specified for LockTransactionForCancellation")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, pgx.Tx) (bool, error)); ok {
		return rf(ctx, id, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, pgx.Tx) bool); ok {
		r0 = rf(ctx, id, tx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, pgx.Tx) error); ok {
		r1 = rf(ctx, id, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
