// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	model "transaction-processor/internal/model"

	pgx "github.com/jackc/pgx/v5"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, userID, tx
func (_m *UserRepository) GetBalance(ctx context.Context, userID int64, tx ...pgx.Tx) (decimal.Decimal, error) {
	_va := make([]interface{}, len(tx))
	for _i := range tx {
		_va[_i] = tx[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, userID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...pgx.Tx) (decimal.Decimal, error)); ok {
		return rf(ctx, userID, tx...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...pgx.Tx) decimal.Decimal); ok {
		r0 = rf(ctx, userID, tx...)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...pgx.Tx) error); ok {
		r1 = rf(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserForUpdate provides a mock function with given fields: ctx, userID, tx
func (_m *UserRepository) GetUserForUpdate(ctx context.Context, userID int64, tx pgx.Tx) (*model.User, error) {
	ret := _m.Called(ctx, userID, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserForUpdate")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, pgx.Tx) (*model.User, error)); ok {
		return rf(ctx, userID, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, pgx.Tx) *model.User); ok {
		r0 = rf(ctx, userID, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, pgx.Tx) error); ok {
		r1 = rf(ctx, userID, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBalance provides a mock function with given fields: ctx, userID, balance, tx
func (_m *UserRepository) UpdateBalance(ctx context.Context, userID int64, balance decimal.Decimal, tx pgx.Tx) error {
	ret := _m.Called(ctx, userID, balance, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, decimal.Decimal, pgx.Tx) error); ok {
		r0 = rf(ctx, userID, balance, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
